config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user, ->(user) { user.role_supervisor? } do
      get 'dashboard', to: "main#dashboard", as: :supervisor_dashboard

      mount Sidekiq::Web => '/sidekiq'
    end

    authenticated :user do
      root to: 'main#dashboard', as: :dashboard
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :login_root
    end
  end

  namespace :profile do
    resources :user, only: %i[update edit]
  end

  namespace :supervisor do
    resources :orders
  end

  resources :orders, only: [:create, :new] do
    member do
      post :accept
      post :deny
    end
  end

  resources :products do
    member do
      post :order
    end
  end

  root to: "main#dashboard"
end

app/views/partials/_flash.html.haml
- if flash.present?
  - flash.each do |type, data|
    = render Shared::Notification::Component.new type: type, data: data

= turbo_frame_tag :turbo_notifications, action: :replace

app/views/partials/_navbar.html.haml
%nav.navbar
  .navbar-container
    %div.flex.justify-start{style: "width: 33.3%;"}
      = link_to "YooNeed", root_path, class: "text-3xl font-bold"

    %div.flex.justify-center{style: "width: 33.3%;"}
      %ul.flex.items-center.gap-10

        - if user_signed_in?
          %li.text-xl.nav-link= link_to "Dashboard", dashboard_path
          %li.text-xl.nav-link= link_to "Products", products_path

          - if current_user.role_supervisor?
            %li.text-xl.nav-link= link_to "Admin", supervisor_orders_path

    %div.flex.justify-end{style: "width: 33.3%;"}
      - if user_signed_in?
        = link_to 'Log Out', destroy_user_session_path, data: { "turbo-method": :delete }, class: "dark-button rounded-lg"

app/views/partials/_sidebar.html.haml
%div.h-full.flex.flex-col.justify-between.px-4
  - if user_signed_in?
    %div
      %ul.flex.flex-col.gap-10.text-center
        %li.text-3xl
          = link_to dashboard_path do
            %i.fa-solid.fa-table-columns
        %li.text-3xl
          = link_to products_path do
            %i.fa-solid.fa-box

          - if current_user.role_supervisor?
            %li.text-3xl.text-center
              = link_to supervisor_orders_path do
                %i.fa-solid.fa-user
    %div
      %ul
        %li.text-3xl.text-center
          = link_to edit_profile_user_path(current_user) do
            %i.fa-solid.fa-gear

app/views/partials/_turbo_notification.html.haml
= render Shared::Notification::Component.new(type: type, data: data)