config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user, ->(user) { user.role_supervisor? } do
      get 'dashboard', to: "main#dashboard", as: :supervisor_dashboard

      mount Sidekiq::Web => '/sidekiq'
    end

    authenticated :user do
      root to: 'main#dashboard', as: :dashboard
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :login_root
    end
  end

  namespace :profile do
    resources :user, only: %i[update edit]
  end

  namespace :supervisor do
    resources :orders
  end

  resources :orders, only: [:create, :new] do
    member do
      post :accept
      post :deny
    end
  end

  resources :products do
    member do
      post :order
    end
  end

  root to: "main#dashboard"
end

app/models/product.rb
class Product < ApplicationRecord

  has_one_attached :image
  has_many :orders, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :packing_type, presence: true

  scope :active?, -> { where(active: true) }

  enum packing_type: { piece: 0, boxes: 1, pack: 2 }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!,            except: %i[index]
  before_action :set_product,  only: %i[show edit update destroy]
  before_action :authorize_product!,  only: %i[edit update destroy]
  after_action  :verify_authorized, only: %i[edit update destroy]

  def index
    @products = Product.all.decorate
  end

  def edit; end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to root_path, notice: "Product was successfully created." }
        format.json { render :index, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to root_path, notice: "Product was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy!

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :packing_type, :active, :image)
    end

  def authorize_product!
    authorize(@product || Product)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/supervisor/products_helper.rb
module Supervisor::ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product&.errors&.full_messages&.any?
    #error_explanation{ "data-turbo-cache" => "false" }
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message
  .field.mb-2.flex.flex-col
    = f.label :name
    = f.text_field :name, class: "w-96"
  .field.mb-2.flex.flex-col
    = f.label :description
    = f.text_area :description, class: "w-96"
  .field.mb-2.flex.flex-col
    = f.label :packing_type
    = f.select :packing_type, options_for_select(@product.decorate.humanized_packing_types, @product.packing_type), class: 'text-light'
  .field.mb-2.flex.flex-col
    = f.label :image
    = f.file_field :image, class: "w-96 mt-2"
  .actions
    = f.submit 'Save', class: "dark-button"

app/views/products/edit.html.haml
%h1.mb-2 Editing product

= render "form"

app/views/products/index.html.haml
%div.flex.flex-col.gap-2
  %h2.text-2xl.font-bold.text-center.uppercase Produkten
  .bg-gray-200.pt-8.pb-4.px-6.rounded-3xl.opacity-1.mb-4
    - @products.each do |product|
      .flex.items-center.justify-between.px-4.py-2.border.bg-white.rounded-xl.mb-4
        .w-full.flex.items-center.justify-between.gap-8.py-2
          %div.w-60
            = image_tag asset_path('wasser.svg'), class: "p-1 rounded-full bg-gray-200", style: "width: 100px;"

          %div.flex.flex-col.items-start.justify-between.gap-8.w-full
            %ul.flex.justify-between.items-center.gap-2.w-full.text-left
              %li.text-md.font-medium Datum
              %li.text-md.font-medium Artikel
              %li.text-md.font-medium Menge

            %ul.flex.justify-between.items-center.gap-2.w-full
              %li= product.created_at
              %li= product.name
              %li= product.packing

          %div.flex.justify-center.items-center.w-96.gap-2
            = link_to "Show", product_path(product.id), class: "bg-blue-800 product-btn hover:bg-blue-700"
            = link_to "Edit", edit_product_path(product.id), class: "bg-teal-800 product-btn hover:bg-teal-700"
            = link_to 'Destroy', product, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "bg-red-800 product-btn hover:bg-red-700"

= link_to 'New Product', new_product_path, class: "product-btn bg-blue-900 product-btn hover:bg-blue-700"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b Description:
  = @product.description
%p
  %b Price:
  = @product.amount
%p
  %b Active:
  = @product.active

= link_to 'Edit', edit_product_path(@product)

= link_to 'Back', products_path